modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "ascendant_arcana"
version = "${version}"
displayName = "Ascendant Arcana"
authors = "anticode"
description = '''
An expansive enchantment overhaul mod
'''
#logoFile = ""

[[dependencies.ascendant_arcana]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ascendant_arcana]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ascendant_arcana]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
